/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'sainlogic adapter settings': {
        'en': 'Adapter settings for sainlogic',
        'de': 'Adaptereinstellungen für sainlogic',
        'ru': 'Настройки адаптера для sainlogic',
        'pt': 'Configurações do adaptador para sainlogic',
        'nl': 'Adapterinstellingen voor sainlogic',
        'fr': "Paramètres d'adaptateur pour sainlogic",
        'it': "Impostazioni dell'adattatore per sainlogic",
        'es': 'Ajustes del adaptador para sainlogic',
        'pl': 'Ustawienia adaptera dla sainlogic',
        'zh-cn': 'sainlogic的适配器设置'
    },
    'Listener settings': {
        'en': 'Listener settings',
        'de': 'Listener-Einstellungen',
        'ru': 'Настройки слушателя',
        'pt': 'Configurações de ouvinte',
        'nl': 'Luisteraar instellingen',
        'fr': "Paramètres d'écoute",
        'it': "Impostazioni dell'ascoltatore",
        'es': 'Configuración del oyente',
        'pl': 'Ustawienia słuchacza',
        'zh-cn': '监听器设置'
    },
    'Scheduler settings': {
        'en': 'Scheduler settings',
        'de': 'Zeitplaneinstellungen',
        'ru': 'Настройки планировщика',
        'pt': 'Configurações do agendador',
        'nl': 'Instellingen planner',
        'fr': 'Paramètres du planificateur',
        'it': 'Impostazioni del programma di pianificazione',
        'es': 'Configuración del programador',
        'pl': 'Ustawienia harmonogramu',
        'zh-cn': '调度程序设置'
    },
    'Unit settings': {
        'en': 'Unit settings',
        'de': 'Geräteeinstellungen',
        'ru': 'Настройки агрегата',
        'pt': 'Configurações da unidade',
        'nl': 'Eenheid instellingen',
        'fr': "Paramètres de l'unité",
        'it': "Impostazioni dell'unità",
        'es': 'Configuración de la unidad',
        'pl': 'Ustawienia jednostek',
        'zh-cn': '单位设置'
    },
    'Active': {
        'en': 'Active',
        'de': 'Aktiv',
        'ru': 'Активный',
        'pt': 'Ativo',
        'nl': 'Actief',
        'fr': 'actif',
        'it': 'Attivo',
        'es': 'Activo',
        'pl': 'Aktywny',
        'zh-cn': '积极的'
    },
    'IP:': {
        'en': 'IP:',
        'de': 'IP:',
        'ru': 'IP:',
        'pt': 'IP:',
        'nl': 'IK P:',
        'fr': 'IP :',
        'it': 'IP:',
        'es': 'IP:',
        'pl': 'IP:',
        'zh-cn': '知识产权：'
    },
    'Port:': {
        'en': 'Port:',
        'de': 'Port:',
        'ru': 'Порт:',
        'pt': 'Port:',
        'nl': 'Port:',
        'fr': 'Port:',
        'it': 'Port:',
        'es': 'Port:',
        'pl': 'Port:',
        'zh-cn': '港口：'
    },
    'path': {
        'en': 'path',
        'de': 'Pfad',
        'ru': 'дорожка',
        'pt': 'caminho',
        'nl': 'pad',
        'fr': 'chemin',
        'it': 'sentiero',
        'es': 'camino',
        'pl': 'ścieżka',
        'zh-cn': '小路'
    },
    'Protocol': {
        'en': 'Protocol',
        'de': 'Protokoll',
        'ru': 'Протокол',
        'pt': 'Protocolo',
        'nl': 'Protocol',
        'fr': 'Protocole',
        'it': 'Protocollo',
        'es': 'Protocolo',
        'pl': 'Protokół',
        'zh-cn': '协议'
    },
    'Forward URL:': {
        'en': 'Forward URL:',
        'de': 'Weiterleitungs-URL:',
        'ru': 'Прямой URL:',
        'pt': 'URL de encaminhamento:',
        'nl': 'Doorstuur-URL:',
        'fr': 'URL de transfert :',
        'it': 'URL di inoltro:',
        'es': 'URL de reenvío:',
        'pl': 'Przekaż adres URL:',
        'zh-cn': '转发网址：'
    },
    'Weatherstation IP:': {
        'en': 'Weatherstation IP:',
        'de': 'Wetterstation-IP:',
        'ru': 'IP-адрес метеостанции:',
        'pt': 'IP da estação meteorológica:',
        'nl': 'Weerstation IP:',
        'fr': 'IP de la station météo :',
        'it': 'IP stazione meteo:',
        'es': 'IP de la estación meteorológica:',
        'pl': 'IP stacji pogodowej:',
        'zh-cn': '气象站IP：'
    },
    'Weatherstation Port:': {
        'en': 'Weatherstation Port:',
        'de': 'Wetterstation-Port:',
        'ru': 'Порт метеостанции:',
        'pt': 'Porto da estação meteorológica:',
        'nl': 'Weerstationpoort:',
        'fr': 'Port de la station météo :',
        'it': 'Porto della stazione meteorologica:',
        'es': 'Puerto de estación meteorológica:',
        'pl': 'Port stacji pogodowej:',
        'zh-cn': '气象站端口：'
    },
    'Intervall:': {
        'en': 'Intervall:',
        'de': 'Intervall:',
        'ru': 'Интервал:',
        'pt': 'Intervall:',
        'nl': 'Interval:',
        'fr': 'Intervalle :',
        'it': 'Intervallo:',
        'es': 'Intervalo:',
        'pl': 'Interwał:',
        'zh-cn': '间隔：'
    },
    'Get Firmware': {
        'en': 'Get Firmware',
        'de': 'Firmware abrufen',
        'ru': 'Получить прошивку',
        'pt': 'Obtenha firmware',
        'nl': 'Firmware ophalen',
        'fr': 'Obtenir le micrologiciel',
        'it': 'Ottieni il firmware',
        'es': 'Obtener firmware',
        'pl': 'Pobierz oprogramowanie układowe',
        'zh-cn': '获取固件'
    },
    'Get Current Data': {
        'en': 'Get Current Data',
        'de': 'Aktuelle Daten abrufen',
        'ru': 'Получить текущие данные',
        'pt': 'Obtenha dados atuais',
        'nl': 'Actuele gegevens ophalen',
        'fr': 'Obtenir les données actuelles',
        'it': 'Ottieni dati attuali',
        'es': 'Obtener datos actuales',
        'pl': 'Uzyskaj aktualne dane',
        'zh-cn': '获取当前数据'
    },
    'Get Max Data': {
        'en': 'Get Max Data',
        'de': 'Maximale Daten abrufen',
        'ru': 'Получить максимальное количество данных',
        'pt': 'Obtenha dados máximos',
        'nl': 'Maximale gegevens ophalen',
        'fr': 'Obtenir le maximum de données',
        'it': 'Ottieni dati massimi',
        'es': 'Obtener datos máximos',
        'pl': 'Uzyskaj maksymalne dane',
        'zh-cn': '获取最大数据'
    },
    'Get Min Data': {
        'en': 'Get Min Data',
        'de': 'Mindestdaten abrufen',
        'ru': 'Получить минимальные данные',
        'pt': 'Obter dados mínimos',
        'nl': 'Min. gegevens ophalen',
        'fr': 'Obtenir des données minimales',
        'it': 'Ottieni dati minimi',
        'es': 'Obtener datos mínimos',
        'pl': 'Uzyskaj minimalne dane',
        'zh-cn': '获取最小数据'
    },
    'Get Daily Max Data': {
        'en': 'Get Daily Max Data',
        'de': 'Tägliche maximale Daten abrufen',
        'ru': 'Получить максимальное количество данных за день',
        'pt': 'Obtenha dados máximos diários',
        'nl': 'Maximale dagelijkse gegevens ophalen',
        'fr': 'Obtenez des données maximales quotidiennes',
        'it': 'Ottieni dati massimi giornalieri',
        'es': 'Obtener datos máximos diarios',
        'pl': 'Uzyskaj dzienne maksymalne dane',
        'zh-cn': '获取每日最大数据'
    },
    'Get Daily Min Data': {
        'en': 'Get Daily Min Data',
        'de': 'Tägliche Min-Daten abrufen',
        'ru': 'Получить ежедневные минимальные данные',
        'pt': 'Obtenha dados mínimos diários',
        'nl': 'Dagelijkse min. gegevens ophalen',
        'fr': 'Obtenir des données minimales quotidiennes',
        'it': 'Ottieni dati minimi giornalieri',
        'es': 'Obtener datos mínimos diarios',
        'pl': 'Uzyskaj dzienne dane minimalne',
        'zh-cn': '获取每日最小数据'
    },
    'Rainfall:': {
        'en': 'Rainfall:',
        'de': 'Regenfall:',
        'ru': 'Осадки:',
        'pt': 'Chuva:',
        'nl': 'Regenval:',
        'fr': 'Précipitations :',
        'it': 'Pioggia:',
        'es': 'Lluvia:',
        'pl': 'Opad deszczu:',
        'zh-cn': '雨量：'
    },
    'Temperature:': {
        'en': 'Temperature:',
        'de': 'Temperatur:',
        'ru': 'Температура:',
        'pt': 'Temperatura:',
        'nl': 'Temperatuur:',
        'fr': 'Température:',
        'it': 'Temperatura:',
        'es': 'Temperatura:',
        'pl': 'Temperatura:',
        'zh-cn': '温度：'
    },
    'Pressure:': {
        'en': 'Pressure:',
        'de': 'Druck:',
        'ru': 'Давление:',
        'pt': 'Pressão:',
        'nl': 'Druk:',
        'fr': 'Pression:',
        'it': 'Pressione:',
        'es': 'Presión:',
        'pl': 'Nacisk:',
        'zh-cn': '压力：'
    },
    'Wind Speed:': {
        'en': 'Wind Speed:',
        'de': 'Windgeschwindigkeit:',
        'ru': 'Скорость ветра:',
        'pt': 'Velocidade do vento:',
        'nl': 'Windsnelheid:',
        'fr': 'Vitesse du vent:',
        'it': 'Velocità del vento:',
        'es': 'Velocidad del viento:',
        'pl': 'Prędkość wiatru:',
        'zh-cn': '风速：'
    },
    'Solar Radiation:': {
        'en': 'Solar Radiation:',
        'de': 'Sonnenstrahlung:',
        'ru': 'Солнечная радиация:',
        'pt': 'Radiação solar:',
        'nl': 'Zonnestraling:',
        'fr': 'Radiation solaire:',
        'it': 'Radiazione solare:',
        'es': 'Radiación solar:',
        'pl': 'Promieniowania słonecznego:',
        'zh-cn': '太阳辐射：'
    }  
};
